# [SELECT PANDAS ROWS BASED ON CONDITION](https://chrisalbon.com/python/data_wrangling/pandas_selecting_rows_on_conditions/)

In [1]:
import os, sys, time
from time import sleep
import pathlib, fnmatch
from pathlib import Path
import sqlite3
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
from sqlalchemy import create_engine

---

## create `engine` from SQL-ALCHEMY

In [3]:
# CREATE SQL ALCHEMY ENGINE
engine = create_engine('sqlite:///e:/_Quotes_Tracker/data/quotes_tracker.db')

In [4]:
# CREATE CONNECTION TO DATABASE (from ENGINE)
conn = engine.connect()

---

# CREATE `PANDAS` DF FROM `SQL QUERY`

In [5]:
# SQL_TABLE?
SQL_Table = pd.read_sql_table(table_name="quotes", con=conn, index_col=["tracking_number"])

In [11]:
SQL_Table  #["close_time"]["close_time"]["turn_around"]

,name,email,type,sent,open_time,close_time,turn_around,notes,initials,account_id,prodflow_quote_number,sap_quote_number,price,company_name,product_number
tracking_number,,,,,,,,,,,,,,,
T00000000001,Raffaella,ultra@ultrasci.it,email,True,2020-01-14 09:06:26.827094,2020-01-14 09:52:12.998358,0 days 00:45:46.171264,None,clr/cb,70599064,011420-787,3118922,None,ULTRA Italia,CUS-00002438
T00000000002,Rune Jorgenson,rmj@analytech.dk,email,True,2020-01-14 11:30:10.220050,2020-01-14 15:54:31.648525,0 days 04:24:21.428475,*Quote to be sent to Agilent rep. Susanne K.\n...,RF/cb/KSR,70209452,011420-793,3119213,None,Analytech,CUS-00002441
T00000000003,Raffaella,ultra@ultrasci.it,email,True,2020-01-14 11:31:59.582988,2020-01-14 11:55:00.000000,,None,clr/SI,70599064,011420-790,3119120,None,ULTRA Italia,CUS-00002440
T00000000004,Glen Arrieta,garrieta@ocwd.com,email,True,2020-01-14 11:46:15.654761,2020-01-14 12:48:00.000000,,None,clr/SI,70339639,011420-791,3119191,None,Orange County Water District,CUS-00002442
T00000000005,Raffaella,ultra@ultrasci.it,email,True,2020-01-14 12:03:37.168555,2020-01-16 11:39:33.472533,1 days 23:35:56.303978,None\n\n,clr/SI,70599064,011420-792,3119216,None,ULTRA Italia,CUS-00002443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T00000000058,Raffaella,ultra@ultrasci.it,email,True,2020-01-17 13:03:01.195807,2020-01-17 15:56:10.218517,0 days 02:53:09.022710,None\n,clr/SI,70599064,011720-809,3124449,None,ULTRA Italia,ICUS-0000980
T00000000059,Raffaella,ultra@ultrasci.it,email,True,2020-01-17 13:03:37.187882,2020-01-17 15:56:44.719470,0 days 02:53:07.531588,None\n,clr/SI,70599064,011720-810,3124452,None,ULTRA Italia,ICUS-0000981
T00000000060,Alicia Dodge,alicia@ietltd.com,email,True,2020-01-17 14:16:57.179095,2020-01-17 15:10:12.218886,0 days 00:53:15.039791,None\n,clr/cb,70007303,011720-816,3124482,None,International Equioment Trading,CUS-00001065
T00000000061,Raffaella,ultra@ultrasci.it,email,False,2020-01-17 14:17:38.871912,None,None,None,clr,70599064,,,None,ULTRA Italia,
T00000000064,Chi Gao,chi.gao@fsns.com,email,False,2020-01-17 14:50:54.408033,None,None,None,clr,70277304,,,None,Food Safety Net Services,

In [ ]:
# REPLACE BLANK SPACES WITH np.NaN

### Method 1: Using Boolean Values

In [34]:
# create vairable with TRUE IF nationatlity is USA
already_sent = SQL_Table['sent'] == "True"

In [35]:
already_sent

tracking_number
T00000000001     True
T00000000002     True
T00000000003     True
T00000000004     True
T00000000005     True
                ...
T00000000058     True
T00000000059     True
T00000000060     True
T00000000061    False
T00000000064    False
Name: sent, Length: 62, dtype: bool

In [25]:
# TRY THE FOLLOWING
try: # {
    length = len(SQL_Table)
    print("LEN == " + str(length))
    # CREATING BOOL SERIES FROM isin()
    already_sent = SQL_Table["sent"].isin(["True"])
    print(len(already_sent))
    # SETTING DATA with "sent" = True < ONLY >
    all_sent = SQL_Table[already_sent]
    print(len(all_sent))
    # CREATE **ANOTHER** BOOL SERIES
    # (ones without any TURN_AROUND)
    newly_sent = all_sent["turn_around"].isin(["None"])
    print(len(newly_sent))
    # }
# }
except: # {
    errorMessage = str(sys.exc_info()[0]) + "\n"
    errorMessage = errorMessage + str(sys.exc_info()[1]) + "\n"
    errorMessage = errorMessage + str(sys.exc_info()[2]) + "\n"
    exc_type, exc_obj, exc_tb = sys.exc_info()
    fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
    typeE = str("TYPE : " + str(exc_type))
    fileE = str("FILE : " + str(fname))
    lineE = str("LINE : " + str(exc_tb.tb_lineno))
    messageE = str("MESG : " + "\n" + str(errorMessage))
    print("\n" + typeE +
                  "\n" + fileE +
                  "\n" + lineE +
                  "\n" + messageE)
# }
else: # {
    print("operation completed successfully..")
# }

LEN == 62
62
48
48
operation completed successfully..

# CREATE CURSOR OFF CONN
c = conn.cursor()

In [ ]:
if __name__ == "__main__": # {
    print(len(SQL_Table))
# }

"""
TAKES IN:
(1) DataFrame
RETURNS:
(1) Corrected Dataframe
"""
def check_quote_completion(the_df): # {
    # TRY THE FOLLOWING
    try: # {
        # LIST TO HOLD RESULTS
        result = []
        # FOR EACH ROW-ENTRY IN "sent" COLUMN
        for value in the_df["sent"]: # {
            if bool(value) is False: # {
                # append nothing
                result.append("None")
            # }
        # }
        else: # {
            # MAKE SURE "turn_around" IS ALSO EMPTY
            if str(the_df["turn_around"]) == "None": # {
                # CREATE TIMESTAMP FOR "meow"
                meow_ts = str(pd.Timestamp.now())[:19]
                # APPEND TO RESULT
                result.append(str(meow_ts))
            # }
            else: # {
                print("\n AND CALCULATED !")
            # }
        # }
        print(str(len(result)))
        # OVERWRITE COLUMN?
        the_df["turn_around"] = result
        print(the_df)
    # }
    except: # {
        errorMessage = str(sys.exc_info()[0]) + "\n"
        errorMessage = errorMessage + str(sys.exc_info()[1]) + "\n"
        errorMessage = errorMessage + str(sys.exc_info()[2]) + "\n"
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        typeE = str("TYPE : " + str(exc_type))
        fileE = str("FILE : " + str(fname))
        lineE = str("LINE : " + str(exc_tb.tb_lineno))
        messageE = str("MESG : " + "\n" + str(errorMessage))
        print("\n" + typeE +
                      "\n" + fileE +
                      "\n" + lineE +
                      "\n" + messageE)
    # }
    else: # {
        print("Operation Completed Successfully..")
        return the_df
    # }
# }

def check_quote_completion(the_df): # {
    # TRY THE FOLLOWING
    try: # {
        # COLUMN TO HOLD RESULTS
        result = []
        for row in the_df.itertuples(): # {
            print("\n===============================")
            # print(len(row))
            print("TRACKING NUM == " + str(row[0]))
            # print(row[0])
            # print(row[1])
            is_sent = str(row[4])
            print("STR == " + str(is_sent))
            print("BOOL == " + str(bool(is_sent)))
            # CHECK CONDITIONS
            if bool(is_sent) == True : # {
                print("SENT.....", end='\t')
                # CHECK IF THIS IS FIRST TIME IT WAS SWITCHED
                if str(row[7]) == "None": # {
                    print(">>> NOT YET!")
                    # CREATE TIMESTAMP
                    meow_ts = str(pd.Timestamp.now())[:19]
                    # APPEND
                    result.append(meow_ts)
                # }
                # ELSE.... IT WAS ALREADY SENT PREVIOUS
                else: # {
                    print(">>> ALREADY!")
                    print(">>> on >>> " + str(row[6]))
                    print(">>> turn_around >>> " + str(row[7]))
                    # APPEND PREVIOUS TIMESTAMP
                    result.append(str(row[7]))
                # }
            # }
            else: # {
                print("NOT EVEN SENT...!")
            # }
        # }
    # }
    except: # {
        errorMessage = str(sys.exc_info()[0]) + "\n"
        errorMessage = errorMessage + str(sys.exc_info()[1]) + "\n"
        errorMessage = errorMessage + str(sys.exc_info()[2]) + "\n"
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        typeE = str("TYPE : " + str(exc_type))
        fileE = str("FILE : " + str(fname))
        lineE = str("LINE : " + str(exc_tb.tb_lineno))
        messageE = str("MESG : " + "\n" + str(errorMessage))
        print("\n" + typeE +
              "\n" + fileE +
              "\n" + lineE +
              "\n" + messageE)
    # }
    else: # {
        print("Operation Completed Successfuly...")
    # }
# }

SQL_Table.to_csv("SQL_Table.csv")